# Generated by Django 4.2.5 on 2023-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
