# Generated by Django 4.2.5 on 2023-09-12 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_menuitem_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="day",
        ),
        migrations.AddField(
            model_name="menu",
            name="day",
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
    ]
